### ISSUE TITLE
Option to disable stretching with a URL parameter?

### ISSUE THREAD

**Issue by ollydev** [Integrated-Media/jsmpeg-vnc#11]
[This code](https://github.com/Integrated-Media/jsmpeg-vnc/blob/master/client/index.html#L18) is commented out, which means the image will stretch/scale to the browser size, this is not always ideal for instance keeping ratio is nice on a desktop, but on a mobile stretching is required.

Perhaps we can disable this with a URL parameter? `localhost:8080/?scale=true`. If that isn't possible maybe ship & serve another html file?

**Comment by BenNottelling** [comment]
If you check out this change I've made it only scale the video on a small screen (such as a mobile device) 
https://github.com/Integrated-Media/jsmpeg-vnc/commit/608b68c20f56e26ea6ff8cfd04adab0f6479b761

**Comment by BenNottelling** [comment]
Bump @ollydev does that solution work for you?

**Comment by ollydev** [comment]
It did indeed fix my issue. :)

**Comment by BenNottelling** [comment]
Sweet!
