### ISSUE TITLE
Last column of window is being extended in the browser.

### ISSUE THREAD

**Issue by ollydev** [Integrated-Media/jsmpeg-vnc#9]
Browser sided the image is being extended right by copying the last column.
Also happens with my external grabber.

No parameters were used. `jsmpeg-vnc.exe "Untitled"`

![Image](https://i.imgur.com/S44TLB2.png)

**Comment by ollydev** [comment]
Just tested on the latest release (two years ago) from phoboslab/jsmpeg-vnc and had the same outcome.

Top half = Viewing in browser.
Bottom half = Actual window.

![img](https://i.imgur.com/QI16PaF.png)

Unsure what is even happening.

**Comment by BenNottelling** [comment]
Interesting. How many pixels is it duplicating? Does using the cropping feature crop it out?

**Comment by BenNottelling** [comment]
Also I just noticed, the bar at the top fo the browser view is black rather than white

**Comment by BenNottelling** [comment]
![browser](https://user-images.githubusercontent.com/17304943/47960305-2144d080-dfb6-11e8-8245-6b528502111e.PNG)
![real](https://user-images.githubusercontent.com/17304943/47960306-2144d080-dfb6-11e8-90ad-6ab280c50d07.PNG)
It looks like I'm having this issue on a smaller scale.

**Comment by ollydev** [comment]
The black is just bitblt failing, but here is the results from using desktop duplication where I get the same result. 

Captured from the entire desktop using desktop duplication (I cropped most of the desktop out):
![img](https://i.imgur.com/PAVRzhp.png)

Paint window captured, using desktop duplication:
![img](https://i.imgur.com/4tiZakt.png)

Very weird!

**Comment by BenNottelling** [comment]
Okay, I've hunted this down to being an issue within jsmpeg, and not the VNC client. If you take a look at this[ blog post](https://phoboslab.org/log/2013/05/mpeg1-video-decoder-in-javascript) on it you can see the same issue with the video on the blog page, but, if you download it and play it with VLC, it's gone. Top picture is the blog, bottom is from VLC.
![blog](https://user-images.githubusercontent.com/17304943/47967126-094d6b00-e00f-11e8-85af-318c8338d88a.PNG)
![vlc](https://user-images.githubusercontent.com/17304943/47967128-0ce0f200-e00f-11e8-9928-3e74bdafd8e6.PNG)
I think this is an issue with lower resolutions, you can see it happening [here](https://jsmpeg.com/perf.html?file=blade-runner-2049-240p.ts&webgl=1&wasm=1&audio=1 ) with the video in 240p, but try bumping it up to 720p and you can't see it happening.

**Comment by ollydev** [comment]
Thanks for digging into this, looks like there has been some activity recently on phoboslab/jsmpeg too, so maybe a fix in the near future!

**Comment by BenNottelling** [comment]
Hopefully! Maybe the issue I created will help :D
